#!/usr/bin/env python3
"""Extract the controller API surface the platform actually uses (CTL-010).

Scans the four integration sources and emits docs/api-surface.lock: one line
per normalized endpoint path with the consumers that reference it. The lock is
the compatibility contract — anything outside it is not promised.
"""
import re, os, glob, sys, collections

ROOTS = {
    'provider': ['/mnt/labpool/pool-manager/internal/controller/provider_http.go',
                 '/mnt/labpool/pool-manager/api/v1alpha1/provisioning_types.go'],
    'driver':   ['/mnt/labpool/lab-webapp/src/lib/consoleDriverAgent.js',
                 '/mnt/labpool/lab-webapp/src/services/embedConsoleProxy.js'],
    'console':  glob.glob('/mnt/labpool/open-automation-platform-console/shell/app/**/*.ts', recursive=True)
              + glob.glob('/mnt/labpool/open-automation-platform-console/shell/app/**/*.tsx', recursive=True),
    'labs':     glob.glob('/mnt/labpool/lab-content/DO467/*/verify.py')
              + glob.glob('/mnt/labpool/lab-content/DO467/*/guided-exercise.md')
              + glob.glob('/mnt/labpool/lab-content/DO467/*/lab-content/labprovisioning-*.yaml')
              + glob.glob('/mnt/labpool/lab-content/DO274/*/verify.py')
              + glob.glob('/mnt/labpool/lab-content/DO274/*/lab-content/labprovisioning-*.yaml'),
}

# api/v2 path fragments: /api/v2/<seg>/... or bare endpoint literals in Go
PAT_FULL = re.compile(r'/api(?:/controller)?/v2/([a-z0-9_]+(?:/[^\s"\'`?&)\\{}]*)?)')
PAT_GO   = re.compile(r'awxPath\("([a-z0-9_]+)"')
PAT_GO2  = re.compile(r'"((?:organizations|users|teams|credentials|credential_types|projects|project_updates|inventories|constructed_inventories|hosts|groups|inventory_sources|inventory_updates|job_templates|jobs|job_events|job_host_summaries|workflow_job_templates|workflow_jobs|workflow_approvals|workflow_job_template_nodes|schedules|notification_templates|labels|instance_groups|instances|execution_environments|tokens|applications|roles|role_definitions|role_user_assignments|role_team_assignments|activity_stream|settings|metrics|ping|me|ad_hoc_commands|bulk|system_job_templates|unified_jobs))(?:/|")')

def normalize(p):
    p = p.split('?')[0].strip('/')
    segs = []
    for s in p.split('/'):
        if not s: continue
        # numeric ids, template expressions, shell/js interpolations, regex tails
        if (re.fullmatch(r'\d+|N', s) or s.startswith(('$', '%', '<', '{', '*'))
                or s.endswith(('$', '*', ',')) or '{' in s or '<' in s):
            segs.append(':id')
        else:
            segs.append(s)
    # collapse trailing :id-only chains produced by regex/glob artifacts
    while segs and segs[-1] == ':id' and (len(segs) == 1):
        segs.pop()
    if not segs: return None
    return '/'.join(segs)

surface = collections.defaultdict(set)
for consumer, files in ROOTS.items():
    for f in files:
        if not os.path.exists(f): continue
        try: text = open(f, errors='ignore').read()
        except OSError: continue
        hits = set()
        for m in PAT_FULL.finditer(text): hits.add(m.group(1))
        if f.endswith('.go'):
            for m in PAT_GO.finditer(text): hits.add(m.group(1))
            for m in PAT_GO2.finditer(text): hits.add(m.group(1))
        for h in hits:
            n = normalize(h)
            if n: surface[n].add(consumer)

# collapse deep :id chains (a/:id/b/:id/c -> keep) and drop obvious junk
rows = sorted((p, sorted(c)) for p, c in surface.items()
              if not re.search(r'[A-Z]|\.\w+$', p))
out = ['# api-surface.lock — endpoints the platform actually uses (CTL-010).',
       '# Generated by tools/extract_api_surface.py; regenerate, never hand-edit.',
       '# path (":id" = numeric or templated segment) | consumers',
       '# Convention: every collection implies its /:id/ detail route (the provider',
       '# builds detail paths by concatenation), and list endpoints imply ?name=,',
       '# ?organization=, ?page_size= filtering.', '']
for p, c in rows:
    out.append(f'{p:70s} | {",".join(c)}')
open(os.path.join(os.path.dirname(__file__), '..', 'docs', 'api-surface.lock'), 'w')\
    .write('\n'.join(out) + '\n')
print(f'{len(rows)} endpoints from {sum(len(v) for v in ROOTS.values())} files')
for p, c in rows[:15]: print(' ', p, c)
